### ISSUE TITLE
Android toolbar does not appear on marker press

### ISSUE THREAD

**Issue by comountainclimber** [react-community/react-native-maps#549]
When pressing the marker on my map component I see:
<img width="900" alt="screen shot 2016-09-07 at 4 38 21 pm" src="https://cloud.githubusercontent.com/assets/13072035/18331070/8b27e76c-7519-11e6-8d01-97414779276c.png">

after interacting with the parent component and updating the state of the component that renders my mapview the toolbar appears:
<img width="1093" alt="screen shot 2016-09-07 at 4 39 19 pm" src="https://cloud.githubusercontent.com/assets/13072035/18331088/a498485e-7519-11e6-986d-f4d81b240139.png">

does anyone know how I can have the toolbar appear by default on marker press?

**Comment by comountainclimber** [comment]
After messing around with this for a while I was able to implement an extremely hacky solution: basically in the parent component that renders the mapview I conditionally update the render function with an empty `<View></View>`component on marker press... For some this invisible update causes the toolbar to appear

**Comment by diogopalhais** [comment]
@comountainclimber hey man can you show me the hack ? :) Im trying to solve this but without success. Can you show me the code that make it work for you ? Thanks

**Comment by comountainclimber** [comment]
@diogopalhais i am by no means advocating that people actually use the following code snippet but it is literally the only solution that worked... good luck!

https://gist.github.com/comountainclimber/5eab875cb84f15dbc7291c18e499e984

**Comment by diogopalhais** [comment]
@comountainclimber Thank you for your help. your code helped me to understand how to turn around this problem. Basically we have to interact with main view when the marker event is called and then by magic the toolbar appears. Thank you for this hack.

**Comment by zolrath** [comment]
I'm finding that if I (improperly) do not supply a key to my Markers when creating them the Android Toolbar shows when I press a marker.

If I fix the issue and add a unique key per Marker, the Toolbar stops showing up when I press a marker.

**Comment by MatthiasDebaere** [comment]
Hello fellow troubled react-native-maps users, I've found a hacky solution which goes like this:

1. Declare a state variable in the constructor of the component where you're using MapView.
```
  constructor(props) {
    super(props)
    this.state = {
      toolbarHackHeight: 0
    }
  }
```
2. Use this variable in the style for the MapView component (i've used some static code here just for this example, you can and should rewrite this*):
```
  render() {
      return (
              <MapView style={ [style.mapView, { height: 200 + this.state.toolbarHackHeight }] }
                     ...>
              { this._renderMarkers() }
            </MapView>
          )
     }
```
3. Change the state variable on each marker click:
 ```
_renderMarkers() {
          return (
                 <MapView.Marker onPress={ this._showToolbarHack }
                                                .... />
                   )
        }

  _showToolbarHack = () => {
    var heightDiff = 0.5 // we don't want to change the height too much so keep it small. I've noticed 0.5 works best, as opposed to 0.1 doesn't work at all, and 0.5 is barely noticeable to the user.
    // switch the height between 0 and 0.5 and back.
    this.setState({
      toolbarHackHeight: this.state.toolbarHackHeight == heightDiff ? this.state.toolbarHackHeight - heightDiff : this.state.toolbarHackHeight + heightDiff
    })
  }
```
Changing the height of the component will trigger the map to re-render and replace it's toolbar, gps location button, ... 
We could do this height-hack once in our code, but I prefer doing it on each marker click: switching between views or putting the app in background will make the map "forget" where it put the toolbar. So we need to do this height-hack again to re-render again keep our toolbar at all times working and visible!

2*: In my case, i'm using absoluteFillObject on my mapview and a legend with a fixed height below the mapview. I change the height of this legend instead of the 'ugly' code in my example, but the thought process remains the same: by changing the (available) height of the mapview component it redraws its toolbar and such.

Please feel free to comment!

**Comment by iiitmahesh** [comment]
@MatthiasDebaere I am very happy with this hack :+1: , but I wanna know **is there any other elegant solution available ?**

**Comment by MatthiasDebaere** [comment]
@iiitmahesh :) other than putting the _showToolbarHack in the "onMarkerPress" event on the MapView component instead of the "onPress" event on the MapView.Marker component, I can't think of an other more elegant way..

I wish anyone with Android knowledge could fix the code in the module, so we don't have to implement these javascript hacks :p

**Comment by iiitmahesh** [comment]
@MatthiasDebaere 
If I put  like below hak is not wotking

`<MapView ref={ref=> { this.map = ref; }} style={[styles.map, { height: AppSizes.screen.height + this.state.toolbarHackHeight }]} >`
```
map: {
        ...StyleSheet.absoluteFillObject,   
    },  
```

**Comment by alextorn** [comment]
@MatthiasDebaere , could you please show us an example of the way that you have mentioned here:

> 2*: In my case, i'm using absoluteFillObject on my mapview and a legend with a fixed height below the mapview. I change the height of this legend instead of the 'ugly' code in my example, but the thought process remains the same: by changing the (available) height of the mapview component it redraws its toolbar and such.

**Comment by MatthiasDebaere** [comment]
It's really simple:

```
<View style={ style.mapContainer }>
          <View style={ style.map }>
            <MapView ref="nearbymap"
                     style={ style.mapView }
                     showsUserLocation={ true }
                     followsUserLocation={ true }
                     toolbarEnabled={ true }
                     loadingEnabled={ true }>
                     { this._renderMarkers() }
            </MapView>
          </View>
          <PopUp height={ 230 + toolbarHackHeight }>
               My legend here
          </PopUp>
</View>
```

and as styling i have the following:

```
mapContainer: {
    width: Metrics.screenWidth,
    height: Metrics.screenHeight - Metrics.presentationNavbarHeight - Metrics.navBarHeight - Metrics.statusBarHeight
  },
  map: {
    flex: 1,
    alignItems: 'center'
  },
  mapView: {
    ...StyleSheet.absoluteFillObject
  }
```

and then implement the `_showToolbarHack` function as onPress of the markers, or onMarkerPress of the container, or somewhere else you'd like to trigger the redraw.

Does this help, or would you like more info?

**Comment by alextorn** [comment]
@MatthiasDebaere , thank you Matthias. It works!

**Comment by efkan** [comment]
I guess this issue can be closed.

Today `toolbarEnabled` property of `MapView` component solves this issue.

Example:
```
<MapView
    toolbarEnabled={false}
>
    {'other components like MapMarker'}
</MapView>
```

**Comment by rborn** [comment]
Closed as solved by https://github.com/react-community/react-native-maps/issues/549#issuecomment-366313775

**Comment by Billy-** [comment]
Do we know which release/version fixed this? :beers:

**Comment by greenais** [comment]
For me the issue isn't solved - with hack above or without, toolbarEnabled={true} doesn't work, no toolbar at all.

**Comment by Bonissauro** [comment]
Me too, @greenais !

I've implemented every suggestion here with no results.

**Comment by greenais** [comment]
@Bonissauro let's re-open this issue as it's obviously not resolved yet.
Guys have quite a number of other opened issues to check comments such closed ones.
They are doing great job - let's help them

**Comment by MasoudShah** [comment]
@FDMatthias your solution worked perfectly. I also had to change the height at the render time (with a bit delay) to show the "find my location" button at the top right corner, otherwise it wouldn't show up. Such a strange bug in react module that hasn't been resolved until now.
