### ISSUE TITLE
Android: View marker does not update when only opacity style changes

### ISSUE THREAD

**Issue by stinju** [react-community/react-native-maps#65]
On a re-render, if the view marker only has an opacity style change, the marker does not reflect the new opacity.  However, if the marker also has a key or text change, the marker does reflect the new opacity.  Example below.  Note that iOS works as expected.  Thanks!

Versions:

```
"react-native": "^0.19.0",
"react-native-maps": "^0.3.0",

Google Nexus 4, 5.1.0 emulator
```

Example:

```
var React = require('react-native');
var {
  StyleSheet,
  View,
  Text,
  Dimensions,
  TouchableOpacity,
  } = React;

var MapView = require('react-native-maps');
var PriceMarker = require('./PriceMarker');

var { width, height } = Dimensions.get('window');

const ASPECT_RATIO = width / height;
const LATITUDE = 37.78825;
const LONGITUDE = -122.4324;
const LATITUDE_DELTA = 0.0922;
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;

var BugPlay = React.createClass({
  getInitialState() {
    return {
      region: {
        latitude: LATITUDE,
        longitude: LONGITUDE,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA,
      },
      coordinate: {
        latitude: LATITUDE,
        longitude: LONGITUDE,
      },
      coordinate2: {
        latitude: LATITUDE + 0.01,
        longitude: LONGITUDE,
      },
      coordinate3: {
        latitude: LATITUDE + 0.02,
        longitude: LONGITUDE,
      },
      amount: 99,
      opacity: 0.5
    };
  },

  changeOpacity() {
    this.setState({opacity: Math.random()});
  },

  render() {
    return (
      <View style={styles.container} opacity={this.state.opacity}>
        <MapView
          style={styles.map}
          initialRegion={this.state.region}
        >
          <MapView.Marker coordinate={this.state.coordinate}>
            <View style={{opacity: this.state.opacity, backgroundColor: 'red'}}>
              <Text style={styles.dollar}>Foo</Text>
            </View>
          </MapView.Marker>
          <MapView.Marker coordinate={this.state.coordinate2}>
            <View style={{opacity: this.state.opacity, backgroundColor: 'red'}}>
              <Text style={styles.dollar} key={this.state.opacity}>Key Change</Text>
            </View>
          </MapView.Marker>
          <MapView.Marker coordinate={this.state.coordinate3}>
            <View style={{opacity: this.state.opacity, backgroundColor: 'red'}}>
              <Text style={styles.dollar}>Text Change {this.state.opacity}</Text>
            </View>
          </MapView.Marker>
        </MapView>
        <View style={styles.buttonContainer}>
          <TouchableOpacity onPress={this.changeOpacity} style={[styles.bubble, styles.button]}>
            <Text style={{ fontSize: 20, fontWeight: 'bold' }}>change opacity</Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  },
});

var styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  bubble: {
    backgroundColor: 'rgba(255,255,255,0.7)',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 20,
  },
  latlng: {
    width: 200,
    alignItems: 'stretch',
  },
  button: {
    width: 200,
    paddingHorizontal: 12,
    alignItems: 'center',
    marginHorizontal: 10,
  },
  buttonContainer: {
    flexDirection: 'row',
    marginVertical: 20,
    backgroundColor: 'transparent',
  },
});

module.exports = BugPlay;
```

**Comment by mvaivre** [comment]
Indeed, in order to be updated the component content must be changed.
Could it be solved with this? -> https://facebook.github.io/react-native/docs/direct-manipulation.html

**Comment by rborn** [comment]
We're trying to cleanup the repo, so please comment/mention me if this is still an issue. Thank you.

**Comment by brunovianarezende** [comment]
Hi, this still happens with me. If I have a marker and only the color of it changes, the change is not displayed. However, if I change the marker's key, it works.

**Comment by rborn** [comment]
@brunovianarezende try to add a key to all the markers and set the style based on the state. IT should work.

**Comment by brunovianarezende** [comment]
@rborn : what worked for me was:

1. have a key in the marker
2. change the style
3. change the key of the marker

in other words, if I only have this:

```
    const key = `${data.key}`

    return (
      <Marker key={key} ...>
        <MyDisplayComponent
          color={markerColor}
        />
      </Marker>
    )
```
and use color as a style inside `MyDisplayComponent`, when color value change it doesn't work.

But, if I have this:

```
    const key = `${data.key}_${markerColor}`

    return (
      <Marker key={key} ...>
        <MyDisplayComponent
          color={markerColor}
        />
      </Marker>
    )
```

when color change, it will work.

**Comment by yuoppp** [comment]
I have the similar case, but i want to change MyDisplayComponent's state by reference. 

```
const key = `${data.key}_${markerColor}`

    return (
      <Marker key={key} ...>
        <MyDisplayComponent
          ref={(c) => this._marker = c}
          color={markerColor}
        />
      </Marker>
    )
```

and then

```
    this._marker.setColor('#FFFFFF');
```

I found that this improves perfomance with 1000+ marker on the map. This works on iOS, but the changes don't display on Android
