### ISSUE TITLE
Android crash when using React Native 0.36.0

### ISSUE THREAD

**Issue by GuelorEmanuel** [react-community/react-native-maps#735]
Upon attempting to load any instance of a MapView, the app crashes with the following stack trace

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.cubeguelor.test, PID: 2619
                                                                     java.lang.NoSuchMethodError: com.facebook.react.uimanager.events.Event.<init>
                                                                         at com.airbnb.android.react.maps.RegionChangeEvent.<init>(RegionChangeEvent.java:16)
                                                                         at com.airbnb.android.react.maps.AirMapView$8.onCameraChange(AirMapView.java:220)
                                                                         at com.google.android.gms.maps.GoogleMap$13.onCameraChange(Unknown Source)
                                                                         at com.google.android.gms.maps.internal.zze$zza.onTransact(Unknown Source)
                                                                         at android.os.Binder.transact(Binder.java:361)
                                                                         at wy.a(:com.google.android.gms.DynamiteModulesB:93)
                                                                         at maps.D.a.a(Unknown Source)
                                                                         at maps.D.a$1.run(Unknown Source)
                                                                         at android.os.Handler.handleCallback(Handler.java:733)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:146)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5487)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                         at dalvik.system.NativeStart.main(Native Method)

**Comment by GuelorEmanuel** [comment]
Fixed the issue by updating play-services-base to the shown version:
compile 'com.google.android.gms:play-services-base:9.4.0'
compile 'com.google.android.gms:play-services-maps:9.4.0'
compile 'com.google.android.gms:play-services-auth:9.4.0'

**Comment by chlee114hk** [comment]
@GuelorEmanuel Updated, but it still crash. When changing to compile 'com.google.android.gms:play-services-maps:+', no crash, but the map show nothing.

**Comment by vincentfretin** [comment]
You can use ```./gradlew app:dependencies``` to see the real used dependencies, you may be using 9.8.0.
You can force a version like this (this fixes a duplicate dex file error in my case with google analytics)
```
compile ('com.google.android.gms:play-services-base:9.4.0'){force = true;}
compile ('com.google.android.gms:play-services-maps:9.4.0'){force = true;}
compile ('com.google.android.gms:play-services-auth:9.4.0'){force = true;}
compile ('com.google.android.gms:play-services-analytics:9.4.0'){force = true;}
```

**Comment by chlee114hk** [comment]
@vincentfretin Thanks a lot for help. I am actually using 10.0.1. I have no crash now, but I got an empty map like this
![screen shot 2017-01-10 at 5 30 40 pm](https://cloud.githubusercontent.com/assets/1836753/21801056/0a01f372-d75b-11e6-9025-64d730013561.png)

**Comment by alvelig** [comment]
Stick to #1773 for compatibility

@chlee114hk this is API_KEY problem.
