### ISSUE TITLE
Callout behind markers

### ISSUE THREAD

**Issue by magrinj** [react-community/react-native-maps#865]
Hello everyone,

It's been a while since this bug persist and it's really annoying, I try to find a solution, but I can't find anything for the moment. So, if someone else can look into the code and try to fix it :) 
The bug happen when you use a custom callout with a custom marker, the click on the marker is not triggered, because the press zone got the same size than the native marker.
So I try to call `showCallout` function when my custom makers is pressed, that's working but now my callout is often behind the markers depending on the render order.

Similar issues are here: #777, #751, #662, #561, #553, #418, #314 

The problem apparently append since July... :/

**Comment by esutton** [comment]
@magrinj Fixed for me.  After updating from 0.11 to 0.12.1 minutes ago.

**Comment by magrinj** [comment]
@esutton I also update to `react-native-maps@0.12.1` and the problem still happened, how did you solve it ? Did you use custom markers with callout ?

**Comment by kamiranoff** [comment]
Reproducing the bug here as well. My Markers and Callouts are rendered through a loop (.map)

**Comment by esutton** [comment]
@magrinj I did nothing.  I assumed upgrading to react-native-maps@0.12.1 fixed it.  I do not recall updating anything else.

Since I do not know what else could have fixed it, here are all packages:
```
  "dependencies": {
    "buffer": "^5.0.1",
    "color": "^1.0.1",
    "merge": "^1.2.0",
    "multiplier": "^0.1.0",
    "react": "~15.4.0-rc.4",
    "react-native": "^0.38.1",
    "react-native-app-info": "0.0.6",
    "react-native-app-intro": "^1.1.4",
    "react-native-device-info": "^0.9.4",
    "react-native-document-controller": 
    "react-native-fs": "^2.0.1-rc.2",
    "react-native-i18n": "0.1.1",
    "react-native-image-picker": "^0.24.1",
    "react-native-maps": "^0.12.1",
    "react-native-orientation": "git+https://github.com/yamill/react-native-orientation",
    "react-native-progress": "^3.2.0",
    "react-native-router-flux": "3.37.0",
    "react-native-share": "^1.0.10",
    "react-native-svg": "^4.3.1",
    "react-native-swipeout": "git+https://github.com/magrinj/react-native-swipeout",
    "react-native-transformable-image": "0.0.18",
    "react-native-uuid": "^1.4.9",
    "react-native-vector-icons": "^3.0.0",
    "react-native-view-transformer": "0.0.28",
    "react-redux": "4.4.6",
    "react-timer-mixin": "^0.13.3",
    "realm": "^0.15.0",
    "redux": "3.6.0",
    "redux-thunk": "2.1.0",
    "victory-native": "^0.4.0",
    "xmldom": "^0.1.22"
  },
```

**Comment by magrinj** [comment]
Thanks @esutton for your `package.json`, my tests was with `react-native@0.36.1`, I'm going to test with `react-native@0.38.1`, to see if the problem was solved by react-native :)

**Comment by kamiranoff** [comment]
Upgrading to react-native@0.38.1 and react-native-maps@0.12.1 did not solve it for me

` 
 onMarkerPressed(marker) {
    this[marker].showCallout();
  }

  renderCallout(marker) {
    return (
      <MapView.Callout>
        <View>
        <Text>Hello</Text>
        </View>
      </MapView.Callout>
    );
  }

  render() {
    return (
      <MapView
        ref={(c) => { this.mapViewRef = c; }}
      >
        {this.props.pointsMap.map((marker, i) => (

          <MapView.Marker
            coordinate={{ latitude: marker.lat, longitude: marker.lng }}
            key={marker.code}
            title={marker.title}
            image={image}
            centerOffset={{ x: 0, y: 0 }}
            onPress={() => this.onMarkerPressed(`marker + ${i}`)}
            ref={(c) => { this[`marker + ${i}`] = c; }}
          >
            {this.renderCallout(marker)}
          </MapView.Marker>
        ))}
      </MapView>
    );
  }
`

That is a simplified version of my code. Some callouts are rendered above some markers, some markers render above some callout. It seems  that the markers and callout are stacked one after the other in the loop and therefore they zIndex coincide with their order in the loop

**Comment by magrinj** [comment]
Anyone ? @lelandrichardson @christopherdro @spikebrehm @felipecsl @gilbox ? :)

**Comment by vivekmago** [comment]
Same issue here the callout does not render

**Comment by skoob13** [comment]
Have the same issue. I have tried this [solution](https://github.com/airbnb/react-native-maps/pull/936), but apparently it works only with static data. With dynamic data is the same issue, when new markers doesn't call callouts.

**Comment by sandman45** [comment]
I am seeing the same thing.. 

Also when I click on the icon it doesn't open the callout.  I have to click to the left or right of the Icon for the callout to show.  When the Callout is shown it is almost always behind the icons.

![screen shot 2017-03-14 at 11 47 16 am](https://cloud.githubusercontent.com/assets/1713969/23914578/fe6ac7b4-08ab-11e7-9b4c-1782bb06ed40.png)


here is some of my package.json

``` "react": "^15.4.2",
    "react-native": "^0.41.2",
    "react-native-code-push": "^1.17.1-beta",
    "react-native-device-info": "^0.9.9",
    "react-native-drawer": "^2.3.0",
    "react-native-fetch-blob": "^0.10.2",
    "react-native-fs": "^2.1.0-rc.1",
    "react-native-global-props": "^1.1.1",
    "react-native-i18n": "^1.0.0",
    "react-native-maps": "^0.13.0",
```


here is how im using MapView
```
 <MapView
      style={styles.map}
      region={{
        latitude: list[0].lat,
        longitude: list[0].lng,
        latitudeDelta: 0.25,
        longitudeDelta: 0.25,
      }}
      mapType={viewType}
    >
      {list.map(marker => (
        <MapView.Marker
          coordinate={{ latitude: marker.lat, longitude: marker.lng }}
          key={marker._id}
          image={marker.paid ? require('../../assets/images/location-marker-premium@2x.png') : require('../../assets/images/location-marker-standard@2x.png')}
        >
          <MapView.Callout
            style={marker.paid ? styles.calloutPremium : styles.callout}
            showCallout={showFacilityDetails}
          >
            <TouchableHighlight
              underlayColor="ghostwhite"
              onPress={showFacilityDetails}
            >
              <View>
                <Text style={styles.calloutTitle}>{marker.provName}</Text>
                <Image
                  style={marker.paid ? styles.calloutImagePaid : styles.calloutImageHide}
                  source={house}
                />
                <Text style={styles.calloutDesc}>{marker.address}</Text>
              </View>
            </TouchableHighlight>
          </MapView.Callout>
        </MapView.Marker>
      ))}
    </MapView>
```

**Comment by iiitmahesh** [comment]
@sandman45 DId you find any solution?  I have a same problem..!

**Comment by sandman45** [comment]
@iiitmahesh  no i have not.  I tried zIndex and other things and it didn't work.  Product here at my company agreed to just wait until this is fixed.  So until then we will just use the default pin markers.

**Comment by bruzenak** [comment]
Having this issue as well and have a hacked fix. A cursory glance at the objective c shows that the callout view is added to the custom annotation view. The custom annotation view's zIndex is set in the order it's added to the map. So by definition the older annotation callouts will appear beneath the new ones, as they inherit the z-index from their parent (the marker annotation). I'm pretty sure this is the root cause of the problem.

My hack is to update the zIndex based on the state of the component. When a marker is tapped, I update the state to track the tapped marker. Where the marker is defined, I set the zIndex to a high zIndex if the ref is equivalent to the tapped marker ref. If a marker wasn't just selected, I push its zIndex to zero. This brings the marker to the top, thus ensuring it's z-order is higher than that of all the other markers. This 'fixes' this bug, at the cost of causing the annotation to pop to the top if it's overlapping other annotations.

**Comment by frmdstryr** [comment]
@bruzenak, care to share your changes or perhaps submit a PR?

**Comment by bruzenak** [comment]
@frmdstryr I didn't make any changes to the core code. Didn't have time for a proper fix. Basically, I just registered an on click handler for that marker and when it's hit, I grab it via reference and up the z-order.

**Comment by esutton** [comment]
@magrinj I was wrong - update to react-native-maps@0.12.1 did not fix.

I am using 
```
"react-native": "0.42.3",
"react-native-maps": "^0.13.1",
```

<img width="381" alt="screen shot 2017-04-11 at 2 15 44 pm" src="https://cloud.githubusercontent.com/assets/6115047/24926500/659ed3f0-1ec1-11e7-82c6-5624a25d5824.png">

I am trying to understand what the @bruzenak zIndex hack looks like without finding something that works yet.

**Comment by Norchene** [comment]
I have the same problem. Did any one find a solution ?

**Comment by bruzenak** [comment]
Sorry, had a series of enormously busy weeks, but meant to come back and post more on my 'solution'. Here's what I have, roughly. View (note that I've truncated some stuff to make the example clear. We're inside a loop here that's putting multiple markers on the map based on index):

` <MapView.Marker
            ...
            onPress={() => this.onCalloutPressed(index)}
            ref={`callout-${index}`}
            zIndex={this.state.selectedCalloutIndex === index ? 999 : 0}
          >`

onCalloutPressed:

`onCalloutPressed (index) {
    let calloutRef = `callout-${index}`
    let item = this.refs[calloutRef]
    this.setState({ selectedCalloutIndex: index })

    ...
  }`

This is gross, as it effectively re-renders on tap. It's also a non-elegant solution in that it pushes the index of everything NOT the current callout back to zero. But I've found that it fixes the issue with a minimum of code.

**Comment by frmdstryr** [comment]
Seems to work well here, thanks for taking the time to share!

**Comment by GingerBear** [comment]
I have the same issue that maker overlap callout, and I was able it fix it by cleaning the state before set the state. 
```js
        this.setState({ stores: [] }, () => {
          this.setState({
            stores: stores
          });
        });
```

**Comment by ngandhy** [comment]
Does this fix work for you guys?
https://github.com/airbnb/react-native-maps/pull/1405

**Comment by ischenkodv** [comment]
I have found that the problem is in the `getAnnotationView` function of `AIRMapMarker.m` file. For custom markers it returns the `self` object:
```objective-c
- (MKAnnotationView *)getAnnotationView
{
    if ([self shouldUsePinView]) {
        // pin annotation view
        return _pinView;
    } else {
        self.layer.zPosition = self.zIndex;
        return self;
    }
}
```
And in this case I see the callout is shown under some of the custom markers. I tried to create my own annotation view and it works for me:
```objective-c
@implementation AIRMapMarker {
    BOOL _hasSetCalloutOffset;
    RCTImageLoaderCancellationBlock _reloadImageCancellationBlock;
    MKPinAnnotationView *_pinView;
    MKAnnotationView *_customPinView; // <---------- add this line
}

// This function adds react subviews to the custom annotation view, instead of to the AIRMapMarker.
- (void)didUpdateReactSubviews
{
    if (_customPinView != nil)  {
        for (UIView *subview in self.sortedReactSubviews) {
            [_customPinView addSubview:subview];
        }
    }
}

- (MKAnnotationView *)getAnnotationView
{
    if ([self shouldUsePinView]) {
        if (_pinView == nil) {
            _pinView = [[MKPinAnnotationView alloc] initWithAnnotation:self reuseIdentifier: nil];
            [self addGestureRecognizerToView:_pinView];
            _pinView.annotation = self;
        }
        _pinView.draggable = self.draggable;
        _pinView.layer.zPosition = self.zIndex;
        if ([_pinView respondsToSelector:@selector(setPinTintColor:)]) {
            _pinView.pinTintColor = self.pinColor;
        }
        return _pinView;
    } else {
        // Create annotation view for custom marker.
        if (_customPinView == nil)  {
            _customPinView = [[MKAnnotationView alloc] initWithAnnotation:self reuseIdentifier:nil];
            [self addGestureRecognizerToView:_customPinView];
            _customPinView.annotation = self;
            for (UIView *subview in self.reactSubviews) {
                [_customPinView addSubview:subview];
            }
        }

        CGPoint annotationPoint = [self.map convertCoordinate:self.coordinate toPointToView:self.map];
        CGRect frame = CGRectMake(annotationPoint.x - self.frame.size.width / 2, annotationPoint.y - self.frame.size.height / 2, self.frame.size.width, self.frame.size.height);
        _customPinView.frame = frame;
        _customPinView.bounds = self.bounds;
        _customPinView.draggable = self.draggable;
        _customPinView.layer.zPosition = self.zIndex;
        return _customPinView;
    }
}
```
After I implemented this fix, my callouts works fine, BUT it has problems with performance when I have huge amount of custom markers. I think I'm close to fixing this but need help with performance improvements.

**Comment by ericlewis** [comment]
@ischenkodv let me know how I can assist.

**Comment by agustind** [comment]
Guys, I've fixed this issue like this:

            let markers = []
		this.state.places.map((item, i) => {
    		markers.push(<MapView.Marker
    			    key={i}
                                ref={comp => this['callout-' + i] = comp}
                                zIndex={0}
                                onPress={() => {
                                         markers.map((marker, index) => {
                                                  this['callout-' + index].setNativeProps({zIndex: 0})
                                         })
                                        this['callout-' + i].setNativeProps({zIndex: 9999})
                                 }}
                                 image={require('../assets/images/marker.png')}
    		             coordinate={{latitude: parseFloat(item.lat), longitude: parseFloat(item.lng)}}>
                    </MapView.Marker>)
              })

**Comment by sebringj** [comment]
I noticed that when I drag the issue goes away so I then tried animating by a very tiny unnoticeable amount in the UI and worked!

Just make sure to keep track of **this.latitude** and **this.longitude** as you are moving around the map.
```
  onMarkerPress = () => {
    // fixes callout overlay bug
    this.refs.map.animateToCoordinate(
      { latitude: this.latitude + 0.00000001, longitude: this.longitude + 0.00000001 },
      0
    )
  }
```

**Comment by kirakik** [comment]
This issue has been opened for almost a year, with no visible actions from the maintainers, and no effort to merge the PRs from members of the community. I am starting to think the only way forward with this library is a fork

**Comment by kirakik** [comment]
This issue has been opened for almost a year, with no visible actions from the maintainers, and no effort to merge the PRs from members of the community. I am starting to think the only way forward with this library is a fork

**Comment by alvelig** [comment]
Actually I was able to find a workaround, thanks to @sebringj's suggestion, but in native code: 
SMCalloutView.m
```
    // we may need to scoot over to the left or right to point at the correct spot
    CGFloat adjustX = 0;
    if (anchorX < minPointX) adjustX = anchorX - minPointX;
    if (anchorX > maxPointX) adjustX = anchorX - maxPointX;
    
// add this to make it move a little even if no adjustments are required
    if(adjustX == 0) { adjustX = 5; }
```
But it only works in most cases, in some cases the adjustment is not enough.

**Comment by olofd** [comment]
I use this for this issue, works for my use case: #1843

**Comment by alvelig** [comment]
#1845 should solve this problem. Please comment if you tested and if there are any bugs detected, as collaborators ask me to have positive replies on my pull request to merge it to master.

**Comment by alvelig** [comment]
Duplicate of #418

**Comment by e-nouri** [comment]
This is not solved, I still have the problem with iOS (MapKit and Google), the callouts comes behind the other markers.

**Comment by sebringj** [comment]
I did notice in using google maps option this just works

**Comment by benjamin3991** [comment]
@agustind,

Your solution worked out for me, however i needed to invert the condition, replaced 0 with 9999 and vice versa.

`
markerList ? markerList.map((provider, index) => (
                    this.calculateMarkersWithinBounds(provider, boundingBox) && <MapView.Marker
                      ref={`callout-${index}`}
                      onPress= {() => {
this.state.markerList.map((marker, refIndex) => {
        if (this.refs && this.refs[`callout-${refIndex}`]) {
          this.refs[`callout-${refIndex}`].setNativeProps({ zIndex: 99999 });
        }
      });
      if (this.refs && this.refs[`callout-${index}`]) {
        this.refs[`callout-${index}`].setNativeProps({ zIndex: 0 });
      }
}}
                      key={provider.id}
                      zIndex={0}
                      >
                        </MapView.Marker>
                      )) :
                      null
                    }
`
Bit slow considering performance, but working solution for now...
Note: Also added a ref check, since it was throwing error of undefined.

**Comment by pqminh** [comment]
+1

**Comment by GarimaMathur07** [comment]
@alvelig I have about 600 markers. So, i am using https://github.com/novalabio/react-native-maps-super-cluster uses MapBox's SuperCluster as clustering engine. I am facing **Callout behind markers** issue. I am using `renderMarker` as follows:

```
<ClusteredMapView
						style={styles.map}
						data={this.state.pins}
						ref={o => (this.mapRef = o)}
						renderMarker={this.renderMarker}
						renderCluster={this.renderCluster}
						fitToElements={ClusteredMapView.ANIMATED_FIT}
						edgePadding={styles.edgePaddingStyle}
						clusteringEnabled={true}
						initialRegion={{
							latitude: this.initialRegionLat,
							longitude: this.initialRegionLong,
							latitudeDelta: this.LATITUDE_DELTA,
							longitudeDelta: this.LONGITUDE_DELTA
						}}
					>
						
					</ClusteredMapView>

```
```
renderMarker (pin) {
	const styles = this.styleSheet();
	return (
		<Marker
			key={pin.id || Math.random()}
			coordinate={pin.location}
			ref={o => (this.marker = o)}
			calloutOffset={{ x: -8, y: 28 }}
			calloutAnchor={{ x: 0.5, y: 0.4 }}
			onCalloutPress={() => this.onPressCallout(pin)}
			image={map_pin.source}
		>
			<Callout tooltip style={styles.customCalloutView}>
				<LocationMarkerCallout title={pin.storeloc.name} description={pin.storeloc.address} />
			</Callout>
		</Marker>
	);
};
```
Can you please suggest how can i resolve this issue.
